/* Confirmed partner time windows. No inferred inventory or automatic reservation. */
(()=>{'use strict';const $=id=>document.getElementById(id),bridge=()=>window.PICKGO_AUTH_BRIDGE;
const kst=stamp=>new Date(new Date(stamp).getTime()+9*3600000).toISOString();
const dateLabel=stamp=>new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(stamp));
const clock=stamp=>new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(stamp));
function https(value){try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password&&u.href.length<=2000?u.href:''}catch{return ''}}
function range(day,start,end,now=Date.now()){if(!/^\d{4}-\d{2}-\d{2}$/.test(day)||!/^\d{2}:\d{2}$/.test(start)||!/^\d{2}:\d{2}$/.test(end))return null;const a=new Date(day+'T'+start+':00+09:00'),b=new Date(day+'T'+end+':00+09:00');if(!Number.isFinite(+a)||!Number.isFinite(+b)||kst(a).slice(0,10)!==day||kst(b).slice(0,10)!==day||+a<=now||+b<=+a||+b-+a>8*3600000||day>kst(now+30*86400000).slice(0,10))return null;return {starts_at:a.toISOString(),ends_at:b.toISOString()}}
function fresh(row,now=Date.now()){const verified=+new Date(row.verified_at),expires=+new Date(row.valid_until);return Number.isFinite(verified)&&Number.isFinite(expires)&&verified<=now&&expires>now&&expires>verified&&expires-verified<=3*3600000&&+new Date(row.ends_at)>now}
function defaults(){const next=new Date(Date.now()+9*3600000+3600000);next.setUTCMinutes(0,0,0);if(next.getUTCHours()>=23){next.setUTCDate(next.getUTCDate()+1);next.setUTCHours(9)}const end=new Date(+next+3600000);return {day:next.toISOString().slice(0,10),start:next.toISOString().slice(11,16),end:end.toISOString().slice(11,16)}}
function seed(day,start,end){const v=defaults();$(day).value=v.day;$(day).min=kst(Date.now()).slice(0,10);$(day).max=kst(Date.now()+30*86400000).slice(0,10);$(start).value=v.start;$(end).value=v.end}
function el(tag,text){const node=document.createElement(tag);node.textContent=text;return node}
function errorText(e){return ['PGRST202','42883','42P01'].includes(e?.code)?'빈 코트 시간대 연결을 준비 중입니다. 기존 구장 목록에서 예약처를 확인해주세요.':e?.code==='23505'?'같은 코트에 겹치는 시간대가 있습니다. 기존 시간대를 수정하거나 공개 중지해주세요.':e?.code==='40001'?'다른 관리자가 변경했습니다. 새로고침 후 다시 확인해주세요.':e?.code==='22023'?'날짜·시간·구장 정보를 확인해주세요. 미래 시간, 같은 날 최대 8시간만 가능합니다.':e?.code==='42501'?'관리자 권한을 확인해주세요.':'정보를 불러오거나 저장하지 못했습니다. 연결을 확인하고 다시 시도해주세요.'}
const dialog=$('availabilityDialog');
if(dialog){let sequence=0,rows=[],selected=null,lastFetched=0;
 const publicCourts=()=>typeof COURTS==='undefined'?[]:COURTS.filter(v=>window.PICKGO_PUBLIC_SCOPE?.allows(v.id));
 const chosenDay=()=>new Date($('availabilityDay').value+'T12:00:00+09:00');
 const labelDay=day=>new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'long',day:'numeric',weekday:'short'}).format(day);
 function regions(){const old=$('availabilityRegion').value;const first=el('option','전체 지역');first.value='';$('availabilityRegion').replaceChildren(first);for(const name of [...new Set(publicCourts().map(v=>v.region))]){const o=el('option',name);o.value=name;$('availabilityRegion').append(o)}$('availabilityRegion').value=publicCourts().some(v=>v.region===old)?old:''}
 seed('availabilityDay','availabilityStart','availabilityEnd');regions();
 function quickDays(){const host=$('availabilityQuickDays');host.replaceChildren();const today=new Date(kst(Date.now()).slice(0,10)+'T12:00:00Z');for(let offset=0;offset<7;offset++){const day=new Date(+today+offset*86400000),value=day.toISOString().slice(0,10),button=el('button',(offset===0?'오늘':offset===1?'내일':new Intl.DateTimeFormat('ko-KR',{timeZone:'UTC',weekday:'short'}).format(day))+' '+(day.getUTCMonth()+1)+'/'+day.getUTCDate());button.type='button';button.className='availability-day-chip';button.setAttribute('aria-pressed',String(value===$('availabilityDay').value));button.addEventListener('click',()=>{$('availabilityDay').value=value;changed()});host.append(button)}}
 function selection(){const day=chosenDay(),end=$('availabilityEnd').value;$('availabilitySelection').textContent=Number.isFinite(+day)&&end?labelDay(day)+' · '+$('availabilityStart').value+' ~ '+end:'같은 날 안에 이용할 수 있는 날짜·시간을 선택해주세요.';quickDays()}
 function official(){const box=$('availabilityOfficialList');box.replaceChildren();const day=chosenDay(),wanted=range($('availabilityDay').value,$('availabilityStart').value,$('availabilityEnd').value);$('availabilityOfficial').hidden=!wanted;if(!wanted)return;const region=$('availabilityRegion').value,weekend=[0,6].includes(day.getUTCDay());for(const venue of publicCourts().filter(v=>!region||v.region===region)){const url=https(weekend?venue.bookingUrlWeekend||venue.bookingUrl:venue.bookingUrl);if(!url)continue;const card=el('article','');card.className='availability-card availability-official-card';card.append(el('h3',venue.name),el('p',labelDay(day)+' · '+$('availabilityStart').value+' ~ '+$('availabilityEnd').value),el('small','잔여 시간은 공식 예약처에서 확인해주세요.'));const actions=el('div','');actions.className='availability-actions';const link=el('a','공식 예약처 열기 ↗');link.href=url;link.target='_blank';link.rel='noopener noreferrer';link.addEventListener('click',event=>{if(!range($('availabilityDay').value,$('availabilityStart').value,$('availabilityEnd').value)||!window.PICKGO_PUBLIC_SCOPE?.allows(venue.id)){event.preventDefault();changed()}});actions.append(link);if(venue.bookingUrlWeekend&&venue.bookingUrl!==venue.bookingUrlWeekend){card.append(el('small',weekend?'주말 예약 페이지로 연결합니다.':'평일 예약 페이지로 연결합니다.'));const other=el('a',weekend?'평일 예약 페이지 보기 ↗':'주말·공휴일 구분 확인 ↗');other.href=https(weekend?venue.bookingUrl:venue.bookingUrlWeekend);other.target='_blank';other.rel='noopener noreferrer';if(other.href)actions.append(other)}card.append(actions);box.append(card)}if(!box.children.length)box.append(el('p','선택한 지역에 연결된 공식 예약처가 아직 없습니다.'))}
 function changed(){sequence++;clear();selection();official();$('availabilitySearchButton').disabled=false;$('availabilityStatus').textContent='선택한 조건으로 확인하려면 위 버튼을 눌러주세요.'}
 function clear(){rows=[];selected=null;$('availabilityResults').replaceChildren();$('availabilityResultsHeading').hidden=true}
 function render(){const box=$('availabilityResults');box.replaceChildren();const live=rows.filter(row=>fresh(row)&&selected&&+new Date(selected.starts_at)>Date.now());for(const row of live){const card=el('article','');card.className='availability-card';card.append(el('h3',row.venue_name+' · '+row.court_label),el('p',row.region+' · '+(row.court_type==='야외'?'실외':row.court_type)+' · '+dateLabel(selected.starts_at)+' ~ '+clock(selected.ends_at)),el('small',(row.source_kind==='operator'?'운영자 확인':'제휴 예약 정보 확인')+' '+dateLabel(row.verified_at)+' · 확인 유효 '+clock(row.valid_until)+'까지'));
 const actions=el('div','');actions.className='availability-actions';const link=el('a','예약처에서 확인 ↗');link.href=https(row.booking_url);link.target='_blank';link.rel='noopener noreferrer';link.addEventListener('click',event=>{if(!fresh(row)||+new Date(selected?.starts_at)<=Date.now()){event.preventDefault();void search();return}});
 const court=el('a','구장 상세');court.href='/court.html?id='+encodeURIComponent(row.venue_id);
 const compose=el('button','예약 후 경기 모집');compose.type='button';compose.addEventListener('click',()=>{if(!fresh(row)||!selected||+new Date(selected.starts_at)<=Date.now()){void search();return}if(window.PICKGO_MATCHES?.composeForSlot({...selected,venue_id:row.venue_id}))dialog.close();else if(bridge()?.getUser())$('availabilityStatus').textContent='구장 목록을 새로고침하고 다시 시도해주세요.'});actions.append(link,court,compose);card.append(actions);box.append(card)}
 $('availabilityResultsHeading').hidden=!live.length;
 if(selected)$('availabilityStatus').textContent=live.length?'선택한 시간 전체를 포함하는 빈 코트 '+live.length+'건 · 최대 100건 표시':'PICKGO에서 확인할 수 있는 최신 빈 시간 정보가 없습니다. 예약 마감이라는 뜻은 아니에요. 아래 공식 예약처에서 확인해주세요.';
 }
 async function search(){const seq=++sequence,day=$('availabilityDay').value,start=$('availabilityStart').value,end=$('availabilityEnd').value,region=$('availabilityRegion').value;clear();selection();official();const wanted=range(day,start,end);if(!wanted){$('availabilityStatus').textContent='미래 날짜·시간을 선택해주세요. 같은 날 최대 8시간, 30일 이내로 검색할 수 있습니다.';return}const db=bridge()?.getClient();if(!db){$('availabilityStatus').textContent='빈 시간 정보를 확인하지 못했습니다. 아래 공식 예약처에서 시간을 확인해주세요.';return}$('availabilitySearchButton').disabled=true;$('availabilityStatus').textContent='확인된 빈 시간대를 찾는 중…';try{const {data,error}=await db.rpc('pickgo_available_courts',{p_day:day,p_start:start,p_end:end,p_region:region});if(seq!==sequence||!dialog.open)return;if(error)throw error;if(!Array.isArray(data))throw Error();for(const row of data){if(!/^court-\d+$/.test(row.venue_id)||typeof row.venue_name!=='string'||typeof row.court_label!=='string'||!https(row.booking_url)||!['operator','partner_api'].includes(row.source_kind)||+new Date(row.starts_at)>+new Date(wanted.starts_at)||+new Date(row.ends_at)<+new Date(wanted.ends_at))throw Error()}rows=data.filter(row=>window.PICKGO_PUBLIC_SCOPE?.allows(row.venue_id));selected=wanted;lastFetched=Date.now();render()}catch(e){if(seq===sequence){clear();$('availabilityStatus').textContent=errorText(e)}}finally{if(seq===sequence)$('availabilitySearchButton').disabled=false}}
 $('availabilitySearch').addEventListener('submit',e=>{e.preventDefault();void search()});$('availabilityOpen').addEventListener('click',()=>{if(!range($('availabilityDay').value,$('availabilityStart').value,$('availabilityEnd').value))seed('availabilityDay','availabilityStart','availabilityEnd');regions();selection();official();dialog.showModal();void search()});$('availabilityClose').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{sequence++;clear();$('availabilitySearchButton').disabled=false});dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});for(const id of ['availabilityDay','availabilityStart','availabilityEnd','availabilityRegion'])$(id).addEventListener('change',changed);setInterval(()=>{if(dialog.open&&selected){if(Date.now()-lastFetched>=60000)void search();else render()}},15000);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&dialog.open)void search()});
}
const panel=$('availabilityAdminPanel');
if(panel){let client=null,sequence=0,epoch=0,editing=null,busy=false;const bound=new WeakSet();
 seed('slotDay','slotStart','slotEnd');$('slotListDay').value=$('slotDay').value;
 function resetEditor(){editing=null;$('availabilityAdminForm').reset();seed('slotDay','slotStart','slotEnd');$('slotVenue').disabled=false;$('slotCourt').readOnly=false;$('slotSave').textContent='확인한 시간대 공개'}
 function reset(){epoch++;sequence++;client=null;editing=null;busy=false;panel.hidden=true;$('availabilityAdminList').replaceChildren();$('availabilityAdminStatus').textContent='';$('slotVenue').replaceChildren(el('option','구장을 선택하세요'));$('slotListVenue').replaceChildren(el('option','전체 구장'));resetEditor();$('slotSave').disabled=false;$('availabilityAdminRefresh').disabled=false}
 function edit(row){if(busy)return;editing=row;$('slotVenue').value=row.venue_id;$('slotVenue').disabled=true;$('slotCourt').value=row.court_label;$('slotCourt').readOnly=true;$('slotDay').value=kst(row.starts_at).slice(0,10);$('slotStart').value=kst(Math.max(+new Date(row.starts_at),Math.ceil((Date.now()+60000)/60000)*60000)).slice(11,16);$('slotEnd').value=kst(row.ends_at).slice(11,16);$('slotUrl').value=row.booking_url;$('slotConfirmed').checked=false;$('slotSave').textContent='다시 확인하고 공개';$('availabilityAdminStatus').textContent='시설에 현재 빈 시간대를 다시 확인한 뒤 저장하세요. 구장·코트 구분은 유지됩니다.';$('availabilityAdminForm').scrollIntoView?.({behavior:'smooth',block:'start'})}
 async function load(){const db=client,seq=++sequence;if(!db)return;$('availabilityAdminRefresh').disabled=true;$('availabilityAdminList').replaceChildren();$('availabilityAdminStatus').textContent='등록 시간대를 불러오는 중…';try{const {data,error}=await db.rpc('pickgo_admin_availability',{p_day:$('slotListDay').value,p_venue:$('slotListVenue').value});if(seq!==sequence||db!==client)return;if(error)throw error;if(!Array.isArray(data))throw Error();for(const row of data){const card=el('article','');card.className='availability-card';card.append(el('h3',row.venue_name+' · '+row.court_label),el('p',dateLabel(row.starts_at)+' ~ '+clock(row.ends_at)),el('small',row.status==='closed'?'공개 중지':fresh(row)?'공개 중 · '+clock(row.valid_until)+'까지':'확인 유효시간 만료 / 지난 시간'));const tools=el('div','');tools.className='availability-actions';const modify=el('button','수정 / 재확인');modify.type='button';modify.disabled=+new Date(row.ends_at)<=Date.now();modify.addEventListener('click',()=>edit(row));tools.append(modify);if(row.status==='available'){const close=el('button','공개 중지');close.type='button';close.addEventListener('click',async()=>{if(busy||db!==client||!window.confirm('이 시간대 공개를 중지할까요?'))return;const generation=epoch;busy=true;close.disabled=true;try{const result=await db.rpc('pickgo_close_availability',{p_id:row.id,p_expected:row.updated_at});if(db!==client||generation!==epoch)return;if(result.error||result.data!==true)throw result.error||Error();if(editing?.id===row.id)resetEditor();await load()}catch(e){if(db===client&&generation===epoch)$('availabilityAdminStatus').textContent=errorText(e)}finally{if(generation===epoch){busy=false;close.disabled=false}}});tools.append(close)}card.append(tools);$('availabilityAdminList').append(card)}$('availabilityAdminStatus').textContent=data.length?'선택 날짜의 등록 시간대 최대 100건 · 공개 중지/만료 포함':'이 날짜에 등록된 시간대가 없습니다.'}catch(e){if(seq===sequence&&db===client){$('availabilityAdminList').replaceChildren();$('availabilityAdminStatus').textContent=errorText(e)}}finally{if(seq===sequence&&db===client)$('availabilityAdminRefresh').disabled=false}}
 async function initialize(db){const generation=epoch,selectedVenue=$('slotVenue').value,filterVenue=$('slotListVenue').value;try{const {data,error}=await db.rpc('pickgo_admin_availability_venues');if(db!==client||generation!==epoch)return;if(error)throw error;if(!Array.isArray(data))throw Error();$('slotVenue').replaceChildren(el('option','구장을 선택하세요'));$('slotVenue').firstChild.value='';$('slotListVenue').replaceChildren(el('option','전체 구장'));$('slotListVenue').firstChild.value='';for(const row of data){const o=el('option',row.region+' · '+row.name);o.value=row.id;o.dataset.url=https(row.booking_url);$('slotVenue').append(o);const filter=el('option',row.name);filter.value=row.id;$('slotListVenue').append(filter)}$('slotVenue').value=selectedVenue;$('slotListVenue').value=filterVenue;await load()}catch(e){if(db===client&&generation===epoch)$('availabilityAdminStatus').textContent=errorText(e)}}
 $('slotVenue').addEventListener('change',()=>{$('slotUrl').value=$('slotVenue').selectedOptions[0]?.dataset.url||'';$('slotConfirmed').checked=false});$('slotReset').addEventListener('click',()=>{if(!busy)resetEditor()});for(const id of ['slotListDay','slotListVenue'])$(id).addEventListener('change',()=>void load());$('availabilityAdminRefresh').addEventListener('click',()=>{if(client&&!busy)void initialize(client)});
 $('availabilityAdminForm').addEventListener('submit',async event=>{event.preventDefault();const db=client,generation=epoch;if(!db||busy)return;const wanted=range($('slotDay').value,$('slotStart').value,$('slotEnd').value),url=https($('slotUrl').value);if(!wanted||!url||!$('slotConfirmed').checked||!$('slotVenue').value||!$('slotCourt').value.trim()){ $('availabilityAdminStatus').textContent='미래 시간·구장·코트 구분·HTTPS 예약처와 운영자 확인을 입력해주세요.';return}const day=$('slotDay').value,args={p_venue:$('slotVenue').value,p_court:$('slotCourt').value.trim(),p_starts:wanted.starts_at,p_ends:wanted.ends_at,p_url:url,p_valid_minutes:Number($('slotValidity').value),p_id:editing?.id||null,p_expected:editing?.updated_at||null};busy=true;$('slotSave').disabled=true;$('availabilityAdminStatus').textContent='확인한 시간대를 공개하는 중…';try{const {data,error}=await db.rpc('pickgo_save_availability',args);if(db!==client||generation!==epoch)return;if(error)throw error;if(!data)throw Error();resetEditor();$('slotListDay').value=day;$('slotListVenue').value=args.p_venue;await load();if(db===client&&generation===epoch)$('availabilityAdminStatus').textContent='시간대를 공개했습니다. 유효시간이 지나면 빈 코트 검색에서 자동 제외됩니다.'}catch(e){if(db===client&&generation===epoch)$('availabilityAdminStatus').textContent=errorText(e)}finally{if(generation===epoch){busy=false;if(db===client)$('slotSave').disabled=false}}});
 window.addEventListener('pickgo:admin-ready',event=>{epoch++;client=event.detail?.client;if(!client){reset();return}const db=client;if(!bound.has(db)){bound.add(db);db.auth.onAuthStateChange((event,session)=>{if(db===client&&(event==='SIGNED_OUT'||event==='SIGNED_IN'||!session))reset()})}panel.hidden=false;void initialize(db)});
}
})();
