/* Source status is separate from confirmed free time windows. */
(()=>{'use strict';const $=id=>document.getElementById(id);const states={catalog_only:'예약 정보 수집 · 잔여 시간 미제공',protected:'예약 정보 수집 · 시간대 API 연동 필요',link_only:'지도 링크 · 예약창 연결 필요',requires_partner_api:'네이버 예약 · 제공처 연동 필요',slots_ok:'시간대 자동 수집',failed:'수집 실패 · 다시 확인 필요',disabled:'자동 수집 중지',stale:'갱신 지연 · 현재 상태 미확인'};const providers={seoul_page:'서울 공공서비스예약',naver_page:'네이버',partner_feed:'승인된 시간대 API'};
const date=value=>new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(value));
function el(tag,text){const node=document.createElement(tag);node.textContent=text;return node}
function safe(url){try{const u=new URL(url);return u.protocol==='https:'&&!u.username&&!u.password?u.href:''}catch{return ''}}
function render(box,rows){box.replaceChildren();for(const row of rows){if(window.PICKGO_PUBLIC_SCOPE&&!window.PICKGO_PUBLIC_SCOPE.allows(row.venue_id))continue;if(!Object.hasOwn(states,row.state)||!Object.hasOwn(providers,row.provider)||!Number.isFinite(new Date(row.checked_at).getTime())||!safe(row.booking_url))throw Error();const card=el('article','');card.className='availability-card';const stale=Date.now()-new Date(row.checked_at)>(row.state==='slots_ok'?15:30)*60000;card.append(el('h3',row.venue_name),el('p',providers[row.provider]+' · '+(stale?states.stale:states[row.state])),el('small','마지막 조회 '+date(row.checked_at)+' (한국시간)'));if(!stale&&row.service_status&&row.service_status!=='상태미확인')card.append(el('small','서비스 상태: '+row.service_status+' · 선택한 날짜·시간의 예약 가능 여부와는 다릅니다.'));const link=el('a','예약처에서 시간 확인 ↗');link.href=safe(row.booking_url);link.target='_blank';link.rel='noopener noreferrer';const actions=el('div','');actions.className='availability-actions';actions.append(link);card.append(actions);box.append(card)}}
if($('bookingSyncPublic')){let sequence=0;async function load(){const seq=++sequence,db=window.PICKGO_AUTH_BRIDGE?.getClient();$('bookingSyncPublicList').replaceChildren();if(!db)return;$('bookingSyncPublicStatus').textContent='예약 정보 연결 상태를 확인하는 중…';try{const {data,error}=await db.rpc('pickgo_booking_sync_status',{p_region:$('availabilityRegion').value});if(seq!==sequence||!$('availabilityDialog').open)return;if(error)throw error;if(!Array.isArray(data))throw Error();render($('bookingSyncPublicList'),data);$('bookingSyncPublicStatus').textContent=data.length?'출처별 예약 정보입니다. 날짜·시간별 빈 코트는 위 검색 결과에서 확인하세요.':'자동 수집 연결 정보가 아직 없습니다. 기존 구장 목록에서 공식 예약처를 확인해주세요.'}catch{if(seq===sequence){$('bookingSyncPublicList').replaceChildren();$('bookingSyncPublicStatus').textContent='자동 수집 정보를 확인하지 못했습니다. 구장 목록의 공식 예약처에서 확인해주세요.'}}}
$('availabilityOpen').addEventListener('click',()=>void load());$('bookingSyncPublicRefresh').addEventListener('click',()=>void load());$('availabilityRegion').addEventListener('change',()=>void load());$('availabilityDialog').addEventListener('close',()=>{sequence++;$('bookingSyncPublicList').replaceChildren()});setInterval(()=>{if($('availabilityDialog').open&&!document.hidden)void load()},60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&$('availabilityDialog').open)void load()});}
if($('bookingSyncAdminPanel')){let client=null,sequence=0;const bound=new WeakSet();function reset(){sequence++;client=null;$('bookingSyncAdminPanel').hidden=true;$('bookingSyncAdminList').replaceChildren();$('bookingSyncAdminStatus').textContent='';$('bookingSyncAdminRefresh').disabled=false}async function load(){const db=client,seq=++sequence;if(!db)return;$('bookingSyncAdminList').replaceChildren();$('bookingSyncAdminRefresh').disabled=true;$('bookingSyncAdminStatus').textContent='자동 수집 상태를 불러오는 중…';try{const {data,error}=await db.rpc('pickgo_booking_sync_status',{p_region:''});if(seq!==sequence||db!==client)return;if(error)throw error;if(!Array.isArray(data))throw Error();render($('bookingSyncAdminList'),data);$('bookingSyncAdminStatus').textContent=data.length?'최근 수집 출처 최대 100건 · 정보 수집과 잔여 시간 수집을 구분합니다.':'수집 실행 내역이 없습니다. 적용 안내의 GitHub Actions 설정 후 수동 실행해주세요.'}catch(e){if(seq===sequence&&db===client){$('bookingSyncAdminList').replaceChildren();$('bookingSyncAdminStatus').textContent=['PGRST202','42883'].includes(e?.code)?'자동 수집 SQL 설정이 필요합니다.':'수집 상태를 불러오지 못했습니다. 새로고침해주세요.'}}finally{if(seq===sequence&&db===client)$('bookingSyncAdminRefresh').disabled=false}}
$('bookingSyncAdminRefresh').addEventListener('click',()=>void load());window.addEventListener('pickgo:admin-ready',event=>{client=event.detail?.client;if(!client){reset();return}const db=client;if(!bound.has(db)){bound.add(db);db.auth.onAuthStateChange((event,session)=>{if(db===client&&(event==='SIGNED_OUT'||event==='SIGNED_IN'||!session))reset()})}$('bookingSyncAdminPanel').hidden=false;void load()});}
})();
