/* Only fixed labels are sent. Never send error messages, URLs, input or tokens. */
(()=>{'use strict';
const VERSION='2.3.4',OPS={match_list:'경기 목록',match_detail:'경기 상세',match_members:'참가자 명단',match_join:'경기 참가',match_leave:'참가 취소',match_cancel:'모집 취소',match_create:'모집 등록',match_update:'모집 수정',match_report:'신고 접수',support_list:'내 문의',support_create:'문의 접수',notifications_list:'알림 목록',notification_read:'알림 확인',my_games:'내 경기'},CATS={network:'연결 오류',permission:'권한 오류',configuration:'설정 오류',conflict:'요청 충돌',unknown:'기타 오류'};
let owner=null;const recent=new Map();
function category(e){const code=e?.code;if(['PGRST202','42883','42P01'].includes(code))return 'configuration';if(['42501','PGRST301','PGRST302'].includes(code)||[401,403].includes(e?.status))return 'permission';if(['23505','40001','40P01'].includes(code))return 'conflict';if(e?.name==='TypeError'||e?.name==='NetworkError'||e?.status===0)return 'network';return 'unknown'}
async function report(operation,error,expectedUser){try{const bridge=window.PICKGO_AUTH_BRIDGE,uid=bridge?.getUser()?.id,db=bridge?.getClient();if(!uid||!db||(expectedUser!==undefined&&uid!==expectedUser)||!Object.hasOwn(OPS,operation))return;if(owner!==uid){owner=uid;recent.clear()}const kind=category(error),key=operation+':'+kind,now=Date.now();if(recent.has(key)&&now-recent.get(key)<60000)return;recent.set(key,now);await db.rpc('pickgo_record_client_error',{p_operation:operation,p_category:kind,p_version:VERSION})}catch{/* Recording must never interrupt the original action. */}}
window.PICKGO_DIAGNOSTICS={report};window.PICKGO_AUTH_BRIDGE?.getClient()?.auth?.onAuthStateChange?.((event,session)=>{if(owner!==session?.user?.id){owner=session?.user?.id||null;recent.clear()}});
const $=id=>document.getElementById(id);if(!$('diagnosticsPanel'))return;
let client=null,sequence=0;const bound=new WeakSet();const time=value=>new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).format(new Date(value));
function el(tag,text){const node=document.createElement(tag);node.textContent=text;return node}
function reset(){sequence++;client=null;$('diagnosticsPanel').hidden=true;$('diagnosticsList').replaceChildren();$('diagnosticsStatus').textContent='';$('diagnosticsRefresh').disabled=false}
async function load(){const db=client,seq=++sequence;if(!db)return;$('diagnosticsList').replaceChildren();$('diagnosticsRefresh').disabled=true;$('diagnosticsStatus').textContent='오류를 불러오는 중…';try{const {data,error}=await db.rpc('pickgo_admin_client_errors',{p_pending:$('diagnosticsPending').checked});if(seq!==sequence||db!==client)return;if(error)throw error;if(!Array.isArray(data))throw Error();for(const row of data){if(!Object.hasOwn(OPS,row.operation)||!Object.hasOwn(CATS,row.category)||!/^\d+\.\d+\.\d+$/.test(row.app_version)||!Number.isFinite(new Date(row.created_at).getTime()))throw Error();const card=el('article','');card.className='panel';card.style.marginTop='12px';card.append(el('h3',OPS[row.operation]+' · '+CATS[row.category]),el('p',time(row.created_at)+' (한국시간) · v'+row.app_version));if(row.reviewed_at)card.append(el('p','확인 완료'));else{const button=el('button','확인 완료');button.type='button';button.className='ghost';button.addEventListener('click',async()=>{if(db!==client)return;button.disabled=true;try{const result=await db.rpc('pickgo_review_client_error',{p_id:row.id});if(db!==client)return;if(result.error||result.data!==true)throw Error();await load()}catch{if(db===client)$('diagnosticsStatus').textContent='확인 상태를 저장하지 못했습니다. 다시 시도하세요.'}finally{button.disabled=false}});card.append(button)}$('diagnosticsList').append(card)}$('diagnosticsStatus').textContent=data.length?'최근 오류 최대 100건 · 확인 완료는 검토 표시이며 오류 수정 여부를 뜻하지 않습니다.':'표시할 오류가 없습니다.'}catch(e){if(seq===sequence&&db===client){$('diagnosticsList').replaceChildren();$('diagnosticsStatus').textContent=['PGRST202','42883'].includes(e?.code)?'오류 확인 SQL 설정이 필요합니다.':'오류 목록을 불러오지 못했습니다. 권한과 연결을 확인해주세요.'}}finally{if(seq===sequence&&db===client)$('diagnosticsRefresh').disabled=false}}
$('diagnosticsRefresh').addEventListener('click',()=>void load());$('diagnosticsPending').addEventListener('change',()=>void load());window.addEventListener('pickgo:admin-ready',event=>{client=event.detail?.client;if(!client){reset();return}const db=client;if(!bound.has(db)){bound.add(db);db.auth.onAuthStateChange((event,session)=>{if(db===client&&(event==='SIGNED_OUT'||event==='SIGNED_IN'||!session))reset()})}$('diagnosticsPanel').hidden=false;void load()});
})();
