/* Personal upcoming games. Scope is enforced by the authenticated RPC. */
(()=>{'use strict';const $=id=>document.getElementById(id),bridge=()=>window.PICKGO_AUTH_BRIDGE;let sequence=0,busy=false;
const el=(tag,text)=>{const node=document.createElement(tag);node.textContent=text;return node};
const time=t=>new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'numeric',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(t));
function clear(){for(const id of ['memberHostedList','memberJoinedList'])$(id).replaceChildren();$('memberHostedCount').textContent='0';$('memberJoinedCount').textContent='0'}
function renderGroup(id,count,rows,empty){$(count).textContent=String(rows.length);const box=$(id);box.replaceChildren();if(!rows.length){const p=el('p',empty);p.className='account-subnote';box.append(p);return}for(const r of rows){const button=el('button','');button.type='button';button.className='member-game'+(r.status==='cancelled'?' cancelled':'');button.append(el('strong',r.venue_name),el('span',time(r.starts_at)+' ~ '+new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(r.ends_at))),el('small',(r.status==='cancelled'?'모집 취소':new Date(r.starts_at)<=new Date()?'진행 중':r.attendees>=r.capacity?'모집 마감':'모집 중')+' · '+r.skill+' · '+r.attendees+'/'+r.capacity+'명 · 상세보기 ↗'));button.addEventListener('click',()=>{$('memberDialog').close();window.PICKGO_NAVIGATE?.('matches');void window.PICKGO_MATCHES?.open(r.id)});box.append(button)}}
async function refresh(){const seq=++sequence,uid=bridge()?.getUser()?.id,db=bridge()?.getClient();clear();if(!uid||!db){$('memberGamesStatus').textContent='로그인하면 내가 모집한 경기와 참가한 경기를 확인할 수 있습니다.';return}$('memberGamesStatus').textContent='내 경기를 불러오는 중…';$('memberGamesRefresh').disabled=true;busy=true;try{const {data,error}=await db.rpc('pickgo_my_games');if(seq!==sequence||uid!==bridge()?.getUser()?.id)return;if(error)throw error;const rows=(data||[]).filter(r=>r.is_host||r.is_joined).sort((a,b)=>(a.status==='cancelled')-(b.status==='cancelled')||new Date(a.starts_at)-new Date(b.starts_at));renderGroup('memberHostedList','memberHostedCount',rows.filter(r=>r.is_host),'내가 모집한 예정 경기가 없습니다.');renderGroup('memberJoinedList','memberJoinedCount',rows.filter(r=>r.is_joined&&!r.is_host),'참가한 예정 경기가 없습니다.');$('memberGamesStatus').textContent='예정·진행 중인 경기와 취소된 예정 모집을 최대 100개 표시합니다.'}catch(e){if(seq!==sequence||uid!==bridge()?.getUser()?.id)return;clear();$('memberGamesStatus').textContent=['PGRST202','42883'].includes(e?.code)?'내 경기 기능을 준비 중입니다. 잠시 후 다시 확인하세요.':'내 경기를 불러오지 못했습니다. 새로고침으로 다시 시도하세요.'}finally{if(seq===sequence){busy=false;$('memberGamesRefresh').disabled=false}}}
$('topAccount').addEventListener('click',()=>{if($('memberDialog').open)void refresh()});$('memberGamesRefresh').addEventListener('click',()=>{if(!busy)void refresh()});
window.PICKGO_MY_GAMES={refreshIfOpen:()=>{if($('memberDialog').open)void refresh()}};
let lastUser=bridge()?.getUser()?.id||null;bridge()?.getClient()?.auth.onAuthStateChange((event,session)=>{const id=session?.user?.id||null;if(id===lastUser)return;lastUser=id;sequence++;busy=false;clear();$('memberGamesRefresh').disabled=false;$('memberGamesStatus').textContent='';if($('memberDialog').open)setTimeout(()=>void refresh(),0)});
})();
