/* Admin-only aggregate metrics. No member email or inquiry content is returned. */
(()=>{'use strict';const $=id=>document.getElementById(id);let client=null,sequence=0;const bound=new WeakSet();
const metrics={members_total:'opsMembersTotal',members_new:'opsMembersNew',matches_new:'opsMatchesNew',matches_active:'opsMatchesActive',participations_active:'opsParticipationsActive',inquiries_pending:'opsInquiriesPending',reports_pending:'opsReportsPending',venues_published:'opsVenuesPublished'};
function clear(){for(const id of Object.values(metrics))$(id).textContent='—'}
function reset(){sequence++;client=null;clear();$('operationsPanel').hidden=true;$('operationsStatus').textContent='';$('operationsRefresh').disabled=false;$('operationsMetrics').setAttribute('aria-busy','false')}
async function load(){const db=client,seq=++sequence;if(!db)return;const days=Number($('operationsPeriod').value);clear();$('operationsRefresh').disabled=true;$('operationsMetrics').setAttribute('aria-busy','true');$('operationsStatus').textContent='운영 현황을 불러오는 중…';try{const {data,error}=await db.rpc('pickgo_admin_overview',{p_days:days});if(seq!==sequence||db!==client)return;if(error)throw error;if(!data||data.period_days!==days)throw Error('invalid_summary');const values={};for(const key of Object.keys(metrics)){const raw=data[key];if(!((typeof raw==='number')||(typeof raw==='string'&&/^\d+$/.test(raw))))throw Error('invalid_metric');const value=Number(raw);if(!Number.isSafeInteger(value)||value<0)throw Error('invalid_metric');values[key]=value}if(!Number.isFinite(new Date(data.computed_at).getTime())||!Number.isFinite(new Date(data.period_start).getTime()))throw Error('invalid_timestamp');for(const [key,id]of Object.entries(metrics))$(id).textContent=new Intl.NumberFormat('ko-KR').format(values[key]);const date=new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'});$('operationsStatus').textContent='조회: '+date.format(new Date(data.computed_at))+' · 기간 시작: '+date.format(new Date(data.period_start))+' (한국시간)'}catch(e){if(seq!==sequence||db!==client)return;clear();$('operationsStatus').textContent=['PGRST202','42883'].includes(e?.code)?'운영 대시보드 SQL 설정이 필요합니다.':e?.code==='42501'?'관리자 권한을 확인해주세요.':'운영 현황을 불러오지 못했습니다. 새로고침으로 다시 시도하세요.'}finally{if(seq===sequence&&db===client){$('operationsRefresh').disabled=false;$('operationsMetrics').setAttribute('aria-busy','false')}}}
$('operationsRefresh').addEventListener('click',()=>void load());$('operationsPeriod').addEventListener('change',()=>void load());
document.querySelectorAll('[data-ops-target]').forEach(button=>button.addEventListener('click',()=>{const target=$(button.dataset.opsTarget);if(target&&!target.hidden)target.scrollIntoView({behavior:'smooth',block:'start'})}));
window.PICKGO_OPS={refresh:()=>void load()};window.addEventListener('pickgo:admin-ready',e=>{client=e.detail?.client;if(!client){reset();return}const db=client;if(!bound.has(db)){bound.add(db);db.auth.onAuthStateChange((event,session)=>{if(db===client&&(event==='SIGNED_OUT'||event==='SIGNED_IN'||!session))reset()})}$('operationsPanel').hidden=false;void load()});
})();
