/* Customer support: private tickets, server-authorized replies, no browser secrets. */
(()=>{'use strict';const $=id=>document.getElementById(id),bridge=()=>window.PICKGO_AUTH_BRIDGE;let busy=false,sequence=0,adminClient=null;
const fields='id,category,subject,message,answer,created_at,answered_at';
const el=(tag,text)=>{const node=document.createElement(tag);node.textContent=text;return node};
const errorText=e=>['PGRST202','42P01','42883'].includes(e?.code)?'문의 서비스를 준비 중입니다. 잠시 후 다시 이용해주세요.':e?.message==='support_rate_limit'?'문의는 30초 간격으로, 하루 최대 5건 접수할 수 있습니다.':e?.code==='42501'?'로그인 상태와 이용 권한을 확인해주세요.':'처리하지 못했습니다. 연결을 확인하고 다시 시도해주세요.';
function card(r){const node=el('article','');node.className='support-ticket';node.append(el('strong',r.subject),el('small',r.category+' · '+new Date(r.created_at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})+' · '+(r.answered_at?'답변 완료':'접수 완료')),el('p',r.message));if(r.answer){const answer=el('p','운영자 답변\n'+r.answer);answer.className='support-answer';node.append(answer)}return node}
function userState(){const signed=!!bridge()?.getUser();$('supportForm').hidden=!signed;$('supportLogin').hidden=signed;$('supportLoginHint').hidden=signed;$('supportHistory').hidden=!signed;return signed}
async function loadOwn(){const seq=++sequence,me=bridge()?.getUser()?.id;$('supportList').replaceChildren();if(!userState()){$('supportStatus').textContent='';return}const db=bridge()?.getClient();$('supportStatus').textContent='내 문의를 불러오는 중…';try{if(!db)throw Error();const {data,error}=await db.from('pickgo_support_tickets').select(fields).eq('user_id',me).order('created_at',{ascending:false}).limit(50);if(seq!==sequence||me!==bridge()?.getUser()?.id)return;if(error)throw error;for(const r of data||[])$('supportList').append(card(r));$('supportStatus').textContent=(data||[]).length?'최근 문의 최대 50건을 표시합니다.':'아직 접수한 문의가 없습니다.'}catch(e){if(seq===sequence&&me===bridge()?.getUser()?.id)$('supportStatus').textContent=errorText(e)}}
if($('supportDialog')){
 const dialog=$('supportDialog');$('topSupport').addEventListener('click',()=>{if(!dialog.open)dialog.showModal();void loadOwn()});
 $('supportClose').addEventListener('click',()=>{if(!busy)dialog.close()});dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault()});
 $('supportLogin').addEventListener('click',()=>{dialog.close();window.PICKGO_AUTH_UI?.open('login')});$('supportRefresh').addEventListener('click',()=>void loadOwn());
 $('supportForm').addEventListener('submit',async e=>{e.preventDefault();if(busy)return;const me=bridge()?.getUser()?.id;if(!me){userState();$('supportStatus').textContent='로그인 후 문의를 접수해주세요.';return}const subject=$('supportSubject').value.trim(),message=$('supportMessage').value.trim();if(subject.length<2||subject.length>100||message.length<10||message.length>2000){$('supportStatus').textContent='제목은 2~100자, 내용은 10~2000자로 작성해주세요.';return}busy=true;$('supportSubmit').disabled=true;$('supportStatus').textContent='문의를 접수하는 중…';try{const {error}=await bridge().getClient().rpc('pickgo_support_create',{p_category:$('supportCategory').value,p_subject:subject,p_message:message});if(me!==bridge()?.getUser()?.id)return;if(error)throw error;$('supportForm').reset();await loadOwn();$('supportStatus').textContent='문의가 접수되었습니다. 답변은 내 문의에서 확인해주세요.'}catch(err){if(me===bridge()?.getUser()?.id)$('supportStatus').textContent=errorText(err)}finally{busy=false;$('supportSubmit').disabled=false}});
 let lastUser=bridge()?.getUser()?.id||null;bridge()?.getClient()?.auth.onAuthStateChange((event,session)=>{const id=session?.user?.id||null;if(id===lastUser)return;lastUser=id;sequence++;$('supportList').replaceChildren();$('supportForm').reset();setTimeout(()=>{userState();if(dialog.open)void loadOwn()},0)});
}
async function loadAdmin(){const seq=++sequence,db=adminClient;if(!db)return;$('supportAdminStatus').textContent='문의를 불러오는 중…';try{const {data,error}=await db.from('pickgo_support_tickets').select(fields).order('created_at',{ascending:false}).limit(100);if(seq!==sequence||db!==adminClient)return;if(error)throw error;const box=$('supportAdminList');box.replaceChildren();for(const r of data||[]){const node=card(r),form=el('form',''),label=el('label','운영자 답변'),text=el('textarea',''),button=el('button',r.answer?'답변 수정':'답변 등록');text.value=r.answer||'';text.required=true;text.minLength=2;text.maxLength=2000;text.rows=4;text.style.cssText='width:100%;padding:10px;margin:10px 0';text.setAttribute('aria-label',r.subject+' 답변');button.type='submit';button.className='primary';form.append(label,text,button);form.addEventListener('submit',async e=>{e.preventDefault();if(busy||db!==adminClient)return;const answer=text.value.trim();if(answer.length<2||answer.length>2000)return;busy=true;button.disabled=true;try{const {error}=await db.rpc('pickgo_support_reply',{p_id:r.id,p_answer:answer});if(db!==adminClient)return;if(error)throw error;await loadAdmin();$('supportAdminStatus').textContent='답변을 저장했습니다. 문의자가 내 문의에서 확인할 수 있습니다.'}catch(err){if(db===adminClient)$('supportAdminStatus').textContent=errorText(err)}finally{busy=false;button.disabled=false}});node.append(form);box.append(node)}$('supportAdminStatus').textContent=(data||[]).length?'최근 문의 최대 100건 표시':'접수된 문의가 없습니다.'}catch(e){if(seq===sequence){$('supportAdminList').replaceChildren();$('supportAdminStatus').textContent=errorText(e)}}}
if($('supportAdminPanel')){const panel=$('supportAdminPanel');$('supportAdminRefresh').addEventListener('click',()=>void loadAdmin());window.addEventListener('pickgo:admin-ready',e=>{adminClient=e.detail?.client;if(!adminClient)return;panel.hidden=false;adminClient.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||!session){sequence++;adminClient=null;$('supportAdminList').replaceChildren();panel.hidden=true}});void loadAdmin()})}
})();
